version: "3"
services:
  rocky8docker:
    build:
      context: .
      args:
        rocky: $RL8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: aursu/rockylinux:${RL8TAG}-gce-build
