# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    archive:
      repo: "puppet/archive"
      ref: "7.0.0"
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.3.0
    bsys:
      repo: aursu/bsys
      ref: 0.4.1
    lsys_nginx:
      repo: aursu/lsys_nginx
      ref: 0.47.0
    apt:
      repo: puppetlabs/apt
      ref: 9.1.0
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      puppet_version: ">= 6.0.0"
    concat:
      repo: puppetlabs/concat
      ref: 9.0.0
    mount_core:
      repo: "puppetlabs/mount_core"
      puppet_version: ">= 6.0.0"
  repositories:
    etcd:
      repo: https://github.com/aursu/puppet-etcd.git
      ref: "tags/v0.4.1"
    kubeinstall:
      repo: https://github.com/aursu/puppet-kubeinstall.git
      ref: "tags/v0.38.4"
    tlsinfo:
      repo: https://github.com/aursu/puppet-tlsinfo.git
      ref: "tags/v0.11.0"
    nginx:
      repo: https://github.com/aursu/puppet-nginx.git
      ref: "tags/v4.4.3"
