# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.3.0
    bsys:
      repo: aursu/bsys
      ref: 0.4.1
  repositories:
    etcd:
      repo: https://github.com/aursu/puppet-etcd.git
      ref: "tags/v0.4.1"
    kubeinstall:
      repo: https://github.com/aursu/puppet-kubeinstall.git
      ref: "tags/v0.27.0"
    tlsinfo:
      repo: https://github.com/aursu/puppet-tlsinfo.git
      ref: "tags/v0.11.0"